AWSTemplateFormatVersion: '2010-09-09'
Description: Criação de RDS para operação farmacêutica
Resources:
  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: farmaceutica-db
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      MasterUsername: admin
      MasterUserPassword: admin12345
      MultiAZ: true
      BackupRetentionPeriod: 7
      PubliclyAccessible: false
